"""RAZ Level L Lesson Plans Part 9: Lessons 17-18."""

LESSONS = []

# ===== 17. SMELLY CLYDE =====
LESSONS.append({
    "title_en": "Smelly Clyde",
    "word_count": 430,
    "topic": "爱在粪堆里打滚的小狗Clyde——幽默故事",
    "objectives": {
        "knowledge": [
            "掌握loyal, manure, sniff, snore, heavenly 等感官类词汇",
            "理解roll over, put ... high in the air, head back home 等短语",
            "学习一般过去时连续叙述与动词过去式",
        ],
        "process": [
            "通过图片和气味联想激活背景",
            "梳理Clyde四次滚动和最后被发现的经过",
            "小组讨论动物的本能行为，培养观察能力",
        ],
        "emotions": [
            "感受幽默故事中动物的天性",
            "理解动物的本能与人类的爱护",
        ],
    },
    "key_points": [
        "感官与动物词汇 (sniff, snore, manure, heaven)",
        "一般过去时连续叙事",
        "roll over / stick ... into the air 等动作短语",
    ],
    "difficult_points": [
        "故事中的夸张表达（heavenly, dread）",
        "动词不规则过去式 (smell-smelled, run-ran)",
    ],
    "methods": ["故事教学", "幽默体验", "动作表演"],
    "preparation": ["小狗Clyde插图", "生词卡", "动作表演道具"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "展示各种动物的'坏习惯'图片，提问Do your pets have any bad habits?",
         "students": "看图讨论。",
         "purpose": "激活背景。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "介绍故事主角Clyde和他的主人Mr. Mora；带读生词卡。",
         "students": "听介绍，跟读生词。",
         "purpose": "建立背景。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 分段阅读；2. 完成'气味之旅'表（鸡粪/牛粪/马粪/猪粪）；3. 重点讲解sniff, snore等词。",
         "students": "分段阅读并填写表格；小组表演动作。",
         "purpose": "训练阅读，落实词汇。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. Discussion：Why does Clyde love smelly things? 2. Role-play：表演故事的结局。",
         "students": "讨论；角色扮演。",
         "purpose": "内化语言，培养幽默感。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与时态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Smelly Clyde\n"
        "Clever dog -> loves manure\n"
        "Chicken -> Cow -> Horse -> Pig -> BATH!\n"
        "★ roll over = 打滚\n"
        "★ sniff ... high in the air = 抬头嗅…"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：写一段你家宠物（或你想象中的宠物）的趣事（英文）。",
        "拓展：阅读英文版《Clifford the Big Red Dog》片段，记录生词。",
    ],
    "vocabulary": [
        {"word": "loyal", "ipa": "/ˈlɔɪəl/", "pos": "adj.", "meaning_zh": "忠诚的",
         "meaning_en": "always supporting and liking a particular person"},
        {"word": "manure", "ipa": "/məˈnʊr/", "pos": "n.", "meaning_zh": "粪肥",
         "meaning_en": "waste matter from animals, used to make soil richer"},
        {"word": "sniff", "ipa": "/snɪf/", "pos": "v.", "meaning_zh": "嗅",
         "meaning_en": "to smell something by taking air in through the nose"},
        {"word": "snore", "ipa": "/snɔːr/", "pos": "v.", "meaning_zh": "打鼾",
         "meaning_en": "to breathe noisily while sleeping"},
        {"word": "heavenly", "ipa": "/ˈhevənli/", "pos": "adj.", "meaning_zh": "极好的",
         "meaning_en": "extremely pleasant or enjoyable"},
        {"word": "dread", "ipa": "/dred/", "pos": "v.", "meaning_zh": "惧怕",
         "meaning_en": "to feel great fear about something that is going to happen"},
        {"word": "wiggle", "ipa": "/ˈwɪɡəl/", "pos": "v.", "meaning_zh": "扭动",
         "meaning_en": "to move with small quick movements from side to side"},
        {"word": "worm", "ipa": "/wɜːrm/", "pos": "v.", "meaning_zh": "蠕动",
         "meaning_en": "to move slowly by twisting the body"},
        {"word": "paddock", "ipa": "/ˈpædək/", "pos": "n.", "meaning_zh": "（马的）围场",
         "meaning_en": "a small field where horses are kept"},
        {"word": "barnyard", "ipa": "/ˈbɑːrnjɑːrd/", "pos": "n.", "meaning_zh": "谷仓旁的场地",
         "meaning_en": "the area near a barn where farm animals are kept"},
        {"word": "pigpen", "ipa": "/ˈpɪɡpen/", "pos": "n.", "meaning_zh": "猪圈",
         "meaning_en": "an enclosed area where pigs are kept"},
        {"word": "odor", "ipa": "/ˈoʊdər/", "pos": "n.", "meaning_zh": "气味",
         "meaning_en": "a smell, especially a strong one"},
    ],
    "phrases": [
        {"phrase": "roll over", "meaning_zh": "打滚",
         "usage": "动词短语",
         "example": "He lay down and rolled over and over."},
        {"phrase": "put ... high in the air", "meaning_zh": "把…高高抬起",
         "usage": "强调抬高动作",
         "example": "Clyde would point his nose high in the air."},
        {"phrase": "pick up a whiff of", "meaning_zh": "闻到一丝…气味",
         "usage": "动词短语，强调闻到一点",
         "example": "Soon he would pick up a whiff of what he loved."},
        {"phrase": "head back home", "meaning_zh": "回家",
         "usage": "动词短语，强调回程",
         "example": "So he headed back home."},
        {"phrase": "slip through", "meaning_zh": "溜过去",
         "usage": "动词短语，强调快速通过",
         "example": "He slipped through the doggy door."},
        {"phrase": "absolutely awful", "meaning_zh": "极其糟糕",
         "usage": "形容词短语，加强语气",
         "example": "You smell absolutely awful."},
    ],
    "grammar": [
        {"point": "一般过去时连续叙事",
         "explanation": "用过去式按时间顺序讲述故事；常用副词then, soon, after that等衔接。",
         "examples": [
            "Clyde ran to the chicken yard.",
            "When he had enough, Clyde stood up.",
            "Soon he smelled another lovely odor.",
         ]},
        {"point": "动词不规则过去式 (smell-smelled/sniffed, run-ran, find-found, smell-smelt)",
         "explanation": "本课常见不规则变化：run-ran, find-found, stick-stuck, smell-smelled, pant-panted。",
         "examples": [
            "Clyde ran to the chicken yard.",
            "Soon he smelled another lovely odor.",
         ]},
        {"point": "When / As soon as 引导时间状语从句",
         "explanation": "when 表当…时；as soon as 表一…就…，强调动作紧接发生。",
         "examples": [
            "When he had enough, Clyde stood up.",
            "As soon as they came into the barnyard, he jumped on it.",
        ]},
    ],
})

# ===== 18. THE LOSER =====
LESSONS.append({
    "title_en": "The Loser",
    "word_count": 505,
    "topic": "总是丢东西的Jae——意外收获友谊",
    "objectives": {
        "knowledge": [
            "掌握drill, encyclopedia, responsibility, signed, umpire 等生活类词汇",
            "理解come home from, knock at door, be friends with 等短语",
            "学习一般过去时叙事与反身代词",
        ],
        "process": [
            "通过预测激活故事情节",
            "梳理Jae三次'丢东西'与三次'交朋友'的过程",
            "小组讨论'失去'与'获得'的辩证关系",
        ],
        "emotions": [
            "理解友谊的珍贵",
            "学会用积极心态看待'失去'",
        ],
    },
    "key_points": [
        "生活与运动词汇 (drill, encyclopedia, responsibility, umpire)",
        "一般过去时叙事 + 反身代词",
        "turn ... into ... 等动词短语",
    ],
    "difficult_points": [
        "美国棒球文化背景",
        "lost 的过去式/过去分词用法",
    ],
    "methods": ["故事教学", "对比分析", "情感讨论"],
    "preparation": ["故事插图", "棒球相关图片", "生词卡"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "提问Have you ever lost something important? How did you feel?",
         "students": "讨论经历。",
         "purpose": "激活背景与情感。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "介绍人物（Jae, Ron, Martina），带读生词卡。",
         "students": "听介绍，跟读生词。",
         "purpose": "建立人物图式。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 分段阅读；2. 完成Jae三次'丢东西-交朋友'对照表；3. 重点讲解responsibility, signed等词。",
         "students": "分段阅读并填写对照表；小组讨论。",
         "purpose": "训练阅读，落实词汇。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. Discussion：What did Jae learn from his losing? 2. Role-play：Jae和Ron的对话。",
         "students": "讨论；角色扮演。",
         "purpose": "内化语言，培养辩证思维。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与时态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "The Loser\n"
        "Lost keys -> Met Ron (umpire friend)\n"
        "Lost book -> Met Martina (dinosaur friend)\n"
        "Lost baseball -> Met puppy\n"
        "★ lose ... -> gain ... = 失去… 收获…"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：续写Jae的故事（5-8句英文）。",
        "拓展：选一个英文短篇故事（如《Charlotte's Web》片段）阅读，记录生词。",
    ],
    "vocabulary": [
        {"word": "drill", "ipa": "/drɪl/", "pos": "n.", "meaning_zh": "训练；练习",
         "meaning_en": "exercises that are practised over and over to learn or perfect a skill"},
        {"word": "encyclopedia", "ipa": "/ɪnˌsaɪkləˈpiːdiə/", "pos": "n.", "meaning_zh": "百科全书",
         "meaning_en": "a book or set of books that gives information about many topics"},
        {"word": "responsibility", "ipa": "/rɪˌspɑːnsəˈbɪləti/", "pos": "n.", "meaning_zh": "责任",
         "meaning_en": "something you are supposed or expected to take care of"},
        {"word": "sign", "ipa": "/saɪn/", "pos": "v.", "meaning_zh": "签名",
         "meaning_en": "to mark one's name on something, often as an autograph"},
        {"word": "umpire", "ipa": "/ˈʌmpaɪər/", "pos": "n.", "meaning_zh": "裁判员",
         "meaning_en": "an official who rules on plays at a sports game"},
        {"word": "stray", "ipa": "/streɪ/", "pos": "adj.", "meaning_zh": "走失的；流浪的",
         "meaning_en": "lost and without a home, especially a pet"},
        {"word": "autograph", "ipa": "/ˈɔːtəɡræf/", "pos": "n.", "meaning_zh": "亲笔签名",
         "meaning_en": "a famous person's signature"},
        {"word": "collar", "ipa": "/ˈkɑːlər/", "pos": "n.", "meaning_zh": "项圈",
         "meaning_en": "a band put around the neck of a dog or cat"},
        {"word": "tag", "ipa": "/tæɡ/", "pos": "n.", "meaning_zh": "标签",
         "meaning_en": "a small piece of paper or cloth attached to something"},
        {"word": "pepper", "ipa": "/ˈpepər/", "pos": "v.", "meaning_zh": "向…提问题",
         "meaning_en": "to ask someone a lot of questions quickly"},
        {"word": "charm", "ipa": "/tʃɑːrm/", "pos": "n.", "meaning_zh": "护身符",
         "meaning_en": "an object believed to bring good luck"},
        {"word": "grin", "ipa": "/ɡrɪn/", "pos": "v.", "meaning_zh": "咧嘴笑",
         "meaning_en": "to smile widely"},
    ],
    "phrases": [
        {"phrase": "come home from", "meaning_zh": "从…回家",
         "usage": "介词短语，强调来源",
         "example": "When Jae came home from school, he couldn't find his keys."},
        {"phrase": "knock at door", "meaning_zh": "敲门",
         "usage": "动词短语",
         "example": "Jae marched to Ron's door and knocked."},
        {"phrase": "be friends with", "meaning_zh": "与…是朋友",
         "usage": "形容词短语",
         "example": "He knew Ron was friends with his father."},
        {"phrase": "lose something", "meaning_zh": "丢失某物",
         "usage": "动词短语",
         "example": "I've lost my dinosaur book."},
        {"phrase": "play catch", "meaning_zh": "玩传接球",
         "usage": "动词短语",
         "example": "Jae and Martina went to the park to play catch with Jae's favorite baseball."},
        {"phrase": "turn ... into ...", "meaning_zh": "把…变成…",
         "usage": "动词短语，强调转变",
         "example": "But every time I lost something, I gained a friend."},
    ],
    "grammar": [
        {"point": "一般过去时 + 间接引语",
         "explanation": "转述他人过去说的话；主句动词用过去式，从句也用过去式（时态一致）。",
         "examples": [
            "Jae's eyes widened as he asked, \"An ump?\"",
            "Dad takes me to their games sometimes.",
        ]},
        {"point": "反身代词 (himself/herself/myself)",
         "explanation": "用于强调主语本人；或与某些动词连用(enjoy oneself, hurt oneself)。",
         "examples": [
            "I can't just sit out here, Jae thought to himself.",
            "But every time I lost something, I gained a friend.",
        ]},
        {"point": "lose (lost-lost) 不规则动词",
         "explanation": "lose的过去式和过去分词均为lost；与find-found相对。",
         "examples": [
            "I've lost my dinosaur book.",
            "But every time I lost something, I gained a friend.",
        ]},
    ],
})
