"""RAZ Level L Lesson Plans Part 7: Lessons 13-14."""

LESSONS = []

# ===== 13. OIL A MESSY RESOURCE =====
LESSONS.append({
    "title_en": "Oil A Messy Resource",
    "word_count": 401,
    "topic": "石油——开采、运输与环境影响",
    "objectives": {
        "knowledge": [
            "掌握energy, leak, oil spill, resource, surface, well 等能源类词汇",
            "理解come from below, rise to the surface, take years to 等短语",
            "学习一般现在时被动语态描述石油的开采与运输",
        ],
        "process": [
            "通过图片激活能源背景",
            "借助流程图梳理石油从开采到泄漏的过程",
            "小组讨论石油的利弊，培养思辨能力",
        ],
        "emotions": [
            "理解能源与环境的辩证关系",
            "培养环保与可持续发展意识",
        ],
    },
    "key_points": [
        "能源与环保词汇 (oil spill, leak, energy, resource, surface)",
        "一般现在时被动语态 (oil is found, is used to make)",
        "It takes ... to do 结构",
    ],
    "difficult_points": [
        "石油开采的科普背景",
        "被动语态在科普文中的多种用法",
    ],
    "methods": ["图片环游", "流程图梳理", "辩论式讨论"],
    "preparation": ["石油开采与泄漏图片", "流程图模板", "生词卡"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "展示石油产品和漏油图片，提问What is oil? Why is it important?",
         "students": "看图讨论。",
         "purpose": "激活能源背景。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "介绍石油的用途和开采方式；带读生词卡。",
         "students": "听介绍，跟读生词。",
         "purpose": "建立背景。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 分段阅读；2. 完成流程图（oil well -> leak -> ocean -> beach -> harm）；3. 重点讲解oil spill, leak等词。",
         "students": "分段阅读并填写流程图；小组讨论。",
         "purpose": "训练阅读，落实词汇与语法。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. Debate：Should we drill for oil under the ocean? 2. 讨论替代能源。",
         "students": "参与辩论。",
         "purpose": "内化语言，培养思辨能力。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与被动结构，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Oil: A Messy Resource\n"
        "Drill -> Pipe up -> Refine -> Transport\n"
        "Problems: oil spill (Deepwater Horizon, Exxon Valdez)\n"
        "★ come from below = 来自地下\n"
        "★ take years to do = 花费多年做…"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：写一段话介绍一种你了解的能源（可再生或不可再生）。",
        "拓展：查阅2010年BP漏油事件，记录3个生词。",
    ],
    "vocabulary": [
        {"word": "energy", "ipa": "/ˈenərdʒi/", "pos": "n.", "meaning_zh": "能源；能量",
         "meaning_en": "the power to do work, make a change or move objects"},
        {"word": "leak", "ipa": "/liːk/", "pos": "v.", "meaning_zh": "泄漏",
         "meaning_en": "to accidentally allow liquid or gas to escape"},
        {"word": "oil spill", "ipa": "/ɔɪl spɪl/", "pos": "n.", "meaning_zh": "漏油事件",
         "meaning_en": "the accidental release of oil into the environment"},
        {"word": "resource", "ipa": "/ˈriːsɔːrs/", "pos": "n.", "meaning_zh": "资源",
         "meaning_en": "a supply of something valuable or useful"},
        {"word": "surface", "ipa": "/ˈsɜːrfɪs/", "pos": "n.", "meaning_zh": "表面；地面",
         "meaning_en": "the outside or top part of a thing; the top of land or water"},
        {"word": "well", "ipa": "/wel/", "pos": "n.", "meaning_zh": "井",
         "meaning_en": "a deep hole dug into the ground to get water, gas or oil"},
        {"word": "drill", "ipa": "/drɪl/", "pos": "v.", "meaning_zh": "钻孔；钻探",
         "meaning_en": "to make a hole in something with a tool or machine"},
        {"word": "rig", "ipa": "/rɪɡ/", "pos": "n.", "meaning_zh": "钻井平台",
         "meaning_en": "a large structure used for drilling for oil"},
        {"word": "tanker", "ipa": "/ˈtæŋkər/", "pos": "n.", "meaning_zh": "油轮",
         "meaning_en": "a ship that carries oil across oceans"},
        {"word": "harm", "ipa": "/hɑːrm/", "pos": "v.", "meaning_zh": "伤害",
         "meaning_en": "to hurt or damage something"},
        {"word": "environment", "ipa": "/ɪnˈvaɪrənmənt/", "pos": "n.", "meaning_zh": "环境",
         "meaning_en": "the air, water and land around us"},
        {"word": "crash", "ipa": "/kræʃ/", "pos": "v.", "meaning_zh": "碰撞；坠毁",
         "meaning_en": "to hit something hard, often causing damage"},
    ],
    "phrases": [
        {"phrase": "come from below", "meaning_zh": "来自地下",
         "usage": "强调来源",
         "example": "Oil comes from below the ground."},
        {"phrase": "rise to the surface", "meaning_zh": "上升到表面",
         "usage": "动词短语，强调上升",
         "example": "The rock keeps the oil from rising to the surface on its own."},
        {"phrase": "get in the water", "meaning_zh": "进入水中",
         "usage": "动词短语",
         "example": "If an oil tanker crashes or sinks, lots of oil can get in the water."},
        {"phrase": "take years to do", "meaning_zh": "花费多年做…",
         "usage": "强调时间成本",
         "example": "It can take years to clean up the mess from a large oil spill."},
        {"phrase": "keep ... from doing", "meaning_zh": "阻止…做…",
         "usage": "动词短语，强调阻止",
         "example": "The pipes keep the oil from getting in the water."},
        {"phrase": "agree on", "meaning_zh": "就…达成一致",
         "usage": "动词短语",
         "example": "Everyone agrees that oil spills are bad."},
    ],
    "grammar": [
        {"point": "一般现在时被动语态",
         "explanation": "结构：主语+am/is/are+过去分词。描述科技文中的常态或客观事实。",
         "examples": [
            "Oil is found in many places.",
            "Some of these places are below land, but others are below the ocean floor.",
            "Oil is used to make gas for cars.",
         ]},
        {"point": "情态动词 can / could / should 表能力或建议",
         "explanation": "can表能力；should表建议；could为can的过去式。",
         "examples": [
            "Lots of oil can get in the water.",
            "They say that oil spills could happen.",
            "Some people think we should not drill for oil under oceans.",
         ]},
        {"point": "If 引导的条件状语从句（真实条件）",
         "explanation": "If + 一般现在时, 主句用will/can/may等。主将从现。",
         "examples": [
            "If an oil tanker crashes or sinks, lots of oil can get in the water.",
        ]},
    ],
})

# ===== 14. OWLS OVERHEAD =====
LESSONS.append({
    "title_en": "Owls Overhead",
    "word_count": 445,
    "topic": "猫头鹰——夜间猎手的特征与习性",
    "objectives": {
        "knowledge": [
            "掌握habitat, prey, species, mysterious, survive, attack 等生物类词汇",
            "理解come in many sizes, fly silently, swallow whole 等短语",
            "学习一般现在时描述动物特征",
        ],
        "process": [
            "通过图片激活猫头鹰相关背景",
            "借助表格梳理不同猫头鹰种类的特征",
            "小组讨论猫头鹰为何能在夜间捕猎",
        ],
        "emotions": [
            "感受自然界的奇妙与生物的多样性",
            "培养保护野生动物的意识",
        ],
    },
    "key_points": [
        "生物类词汇 (habitat, prey, species, mysterious, survive, attack)",
        "一般现在时描述动物特征",
        "形容词比较级 (ten times stronger than)",
    ],
    "difficult_points": [
        "猫头鹰生理特征词汇(pupil, ear, feathers)",
        "数字表达(1,400 mice per year)",
    ],
    "methods": ["图片环游", "信息匹配", "小组讨论"],
    "preparation": ["猫头鹰图片", "对比表格", "生词卡"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "播放猫头鹰叫声，提问What is this sound? Where do owls live?",
         "students": "听声音并讨论。",
         "purpose": "激活背景。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "展示不同种类的猫头鹰图片，带读生词卡。",
         "students": "看图认猫头鹰种类，跟读生词。",
         "purpose": "建立背景。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 分段阅读；2. 完成特征分类表（眼睛/耳朵/羽毛/栖息地/食物）；3. 重点讲解habitat, species等词。",
         "students": "分段阅读并填写分类表；小组讨论。",
         "purpose": "训练信息整合，落实词汇。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. Discussion：Why can owls hunt at night? 2. 想象自己是猫头鹰向同学介绍自己。",
         "students": "讨论；自我介绍。",
         "purpose": "内化语言，培养兴趣。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与时态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Owls Overhead\n"
        "Big eyes -> see in low light\n"
        "Huge ears -> hear prey\n"
        "Soft feathers -> fly silently\n"
        "★ fly silently = 安静地飞\n"
        "★ swallow ... whole = 整吞"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：制作一张猫头鹰的特征图（英文标注）。",
        "拓展：选择一种夜行性动物(nocturnal animal)做英文介绍。",
    ],
    "vocabulary": [
        {"word": "habitat", "ipa": "/ˈhæbɪtæt/", "pos": "n.", "meaning_zh": "栖息地",
         "meaning_en": "the place where a plant or animal lives naturally"},
        {"word": "prey", "ipa": "/preɪ/", "pos": "n.", "meaning_zh": "猎物",
         "meaning_en": "an animal that is hunted and eaten by another animal"},
        {"word": "species", "ipa": "/ˈspiːʃiːz/", "pos": "n.", "meaning_zh": "物种",
         "meaning_en": "a group of living things that are similar and can breed together"},
        {"word": "mysterious", "ipa": "/mɪˈstɪriəs/", "pos": "adj.", "meaning_zh": "神秘的",
         "meaning_en": "strange and not easy to understand"},
        {"word": "survive", "ipa": "/sərˈvaɪv/", "pos": "v.", "meaning_zh": "生存",
         "meaning_en": "to stay alive"},
        {"word": "attack", "ipa": "/əˈtæk/", "pos": "v.", "meaning_zh": "攻击",
         "meaning_en": "to act violently against someone or something"},
        {"word": "pupil", "ipa": "/ˈpjuːpəl/", "pos": "n.", "meaning_zh": "瞳孔",
         "meaning_en": "the black circular part in the centre of the eye"},
        {"word": "continent", "ipa": "/ˈkɑːntɪnənt/", "pos": "n.", "meaning_zh": "大洲",
         "meaning_en": "one of the seven large land masses on Earth"},
        {"word": "pellet", "ipa": "/ˈpelɪt/", "pos": "n.", "meaning_zh": "（猫头鹰吐出的）食团",
         "meaning_en": "a small ball of indigestible parts coughed up by an owl after eating"},
        {"word": "grip", "ipa": "/ɡrɪp/", "pos": "n.", "meaning_zh": "握力",
         "meaning_en": "a very tight hold"},
        {"word": "logging", "ipa": "/ˈlɑːɡɪŋ/", "pos": "n.", "meaning_zh": "伐木",
         "meaning_en": "the activity of cutting down trees for wood"},
        {"word": "scream", "ipa": "/skriːm/", "pos": "v.", "meaning_zh": "尖叫",
         "meaning_en": "to make a loud high cry because of fear or pain"},
    ],
    "phrases": [
        {"phrase": "come in many sizes", "meaning_zh": "大小各异",
         "usage": "动词短语，强调多样性",
         "example": "They come in many sizes and live on every continent except Antarctica."},
        {"phrase": "fly silently", "meaning_zh": "安静地飞",
         "usage": "副词修饰动词",
         "example": "A saw-whet owl flies silently through the trees."},
        {"phrase": "swallow ... whole", "meaning_zh": "整吞",
         "usage": "强调未经咀嚼",
         "example": "Owls can't chew their food. Instead, they often swallow small prey whole."},
        {"phrase": "on the prairie", "meaning_zh": "在草原上",
         "usage": "介词短语表地点",
         "example": "Burrowing owls live mostly on the prairie."},
        {"phrase": "find one", "meaning_zh": "找到一只",
         "usage": "代词one替代同类事物",
         "example": "Barn owls can hear a mouse moving far away and catch one in complete darkness."},
        {"phrase": "turn ... upside down", "meaning_zh": "把…上下颠倒",
         "usage": "强调大幅度转动",
         "example": "They can even turn their heads upside down."},
    ],
    "grammar": [
        {"point": "一般现在时描述动物特征",
         "explanation": "用一般现在时陈述动物客观特征，第三人称单数动词加-s。",
         "examples": [
            "More than two hundred different species of owls live around the world.",
            "Owls can't move their eyes.",
            "Many owls rely on their hearing to hunt.",
         ]},
        {"point": "倍数表达 (twice/three/ten times as ... as ...)",
         "explanation": "倍数 + as + adj./adv. + as 表示倍数关系。",
         "examples": [
            "The grip of some owls can be ten times stronger than a human's grip.",
            "Their tires are twice as tall as a person.",
         ]},
        {"point": "由 who / which / that 引导的定语从句",
         "explanation": "who指人；which/that指物。关系代词在从句中作主语或宾语。",
         "examples": [
            "Owls may seem mysterious, but the way they look and act helps them survive.",
            "Soft feathers that cover owls' bodies help them fly without a sound.",
         ]},
    ],
})
