"""RAZ Level L Lesson Plans Part 1: Lessons 1-4."""

LESSONS = []

# ===== 1. BIG MACHINES =====
LESSONS.append({
    "title_en": "Big Machines",
    "word_count": 550,
    "topic": "建筑工程与运输中的大型机械",
    "objectives": {
        "knowledge": [
            "掌握excavator, bulldozer, crane, scraper等工程与运输机械词汇",
            "理解be used to do, in search of等短语的用法",
            "了解一般现在时被动语态在科普文中的运用",
        ],
        "process": [
            "通过图片预测策略激活背景知识",
            "运用skimming与scanning结合的阅读方式抓取主旨和细节",
            "小组合作完成匹配任务，训练信息整合能力",
        ],
        "emotions": [
            "感受现代工程技术的力量，激发对STEM领域的兴趣",
            "体会人类利用工具改造自然的智慧",
        ],
    },
    "key_points": [
        "工程与运输机械词汇 (excavator, bulldozer, crane, scraper)",
        "be used to do 被动结构",
        "一般现在时被动语态在科普说明文中的运用",
    ],
    "difficult_points": [
        "被动语态的时态变化",
        "by sea / by air / by land 三种运输方式的区分",
    ],
    "methods": ["PWP阅读教学模式", "图片环游法", "任务型阅读"],
    "preparation": ["PPT（含工程机械图片）", "词汇卡片", "课本配套音频"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "展示盖楼、修路、采矿图片，提问What machines do you see? Who uses them?",
         "students": "观察图片，联想已知词汇，尝试英文描述。",
         "purpose": "激活背景知识，引入话题。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "出示封面和目录，介绍篇章结构，带读生词卡。",
         "students": "跟读生词卡，观察封面与目录，预测文章内容。",
         "purpose": "扫除生词障碍，建立文本结构图式。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 速读圈出每段中心词；2. 分组完成'机器-功能'匹配表；3. 重点讲解be used to do结构。",
         "students": "1. 速读抓主旨；2. 小组合作完成任务单；3. 讨论被动结构用法。",
         "purpose": "训练skimming和scanning策略，实现深度阅读。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. Retelling：用本课重点短语复述文章大意；2. Discussion：If you were an engineer, which big machine would you design?",
         "students": "小组代表复述；全班讨论。",
         "purpose": "内化语言知识，提升表达与思辨能力。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结重点词汇与被动结构，布置分层作业。",
         "students": "记录作业。",
         "purpose": "巩固语言点。"},
    ],
    "blackboard": (
        "Big Machines\n"
        "Excavator - dig holes | Bulldozer - move dirt\n"
        "Crane - lift things | Scraper/Grader/Paver - build roads\n"
        "Tugboat/Tanker/Container ship - by water\n"
        "★ be used to do sth. = 被用来做某事\n"
        "★ in search of = 寻找"
    ),
    "homework": [
        "必做：抄写并背诵本课12个重点词汇，每个造一个英文句子。",
        "选做：画一幅未来机器图，用3-5句英文介绍。",
        "拓展：搜索Bagger 288等巨型工程机械，准备课堂分享。",
    ],
    "vocabulary": [
        {"word": "machine", "ipa": "/məˈʃiːn/", "pos": "n.", "meaning_zh": "机器，机械",
         "meaning_en": "a device with moving parts that uses energy to do a particular job"},
        {"word": "steam", "ipa": "/stiːm/", "pos": "n.", "meaning_zh": "蒸汽；水蒸气",
         "meaning_en": "the hot gas that water turns into when it boils"},
        {"word": "coal", "ipa": "/koʊl/", "pos": "n.", "meaning_zh": "煤",
         "meaning_en": "a hard black substance burned to produce heat or power"},
        {"word": "excavator", "ipa": "/ˈekskəveɪtər/", "pos": "n.", "meaning_zh": "挖掘机",
         "meaning_en": "a large machine used for digging"},
        {"word": "bulldozer", "ipa": "/ˈbʊlˌdoʊzər/", "pos": "n.", "meaning_zh": "推土机",
         "meaning_en": "a heavy vehicle used for pushing earth or rubble"},
        {"word": "shovel", "ipa": "/ˈʃʌvəl/", "pos": "n.", "meaning_zh": "铁铲；铲",
         "meaning_en": "a tool with a long handle and a broad blade used to dig or move loose material"},
        {"word": "bucket", "ipa": "/ˈbʌkɪt/", "pos": "n.", "meaning_zh": "铲斗；桶",
         "meaning_en": "a part of a machine used for digging and moving earth"},
        {"word": "crane", "ipa": "/kreɪn/", "pos": "n.", "meaning_zh": "起重机",
         "meaning_en": "a tall machine with a long arm used for lifting heavy objects"},
        {"word": "concrete", "ipa": "/ˈkɑːnkriːt/", "pos": "n.", "meaning_zh": "混凝土",
         "meaning_en": "a hard substance made by mixing cement, sand, and water"},
        {"word": "scraper", "ipa": "/ˈskreɪpər/", "pos": "n.", "meaning_zh": "铲运机",
         "meaning_en": "a large machine that scrapes and removes earth"},
        {"word": "loader", "ipa": "/ˈloʊdər/", "pos": "n.", "meaning_zh": "装载机",
         "meaning_en": "a machine used to load earth or rocks into trucks"},
        {"word": "grader", "ipa": "/ˈɡreɪdər/", "pos": "n.", "meaning_zh": "平地机",
         "meaning_en": "a machine used for making the surface of a road flat"},
        {"word": "paver", "ipa": "/ˈpeɪvər/", "pos": "n.", "meaning_zh": "铺路机",
         "meaning_en": "a machine that lays a road surface"},
        {"word": "roller", "ipa": "/ˈroʊlər/", "pos": "n.", "meaning_zh": "压路机",
         "meaning_en": "a heavy machine used for flattening surfaces"},
        {"word": "tanker", "ipa": "/ˈtæŋkər/", "pos": "n.", "meaning_zh": "油轮；罐车",
         "meaning_en": "a ship or vehicle used for carrying large amounts of liquid"},
        {"word": "barge", "ipa": "/bɑːrdʒ/", "pos": "n.", "meaning_zh": "驳船",
         "meaning_en": "a long flat boat used to carry heavy goods on rivers"},
        {"word": "resource", "ipa": "/ˈriːsɔːrs/", "pos": "n.", "meaning_zh": "资源",
         "meaning_en": "a useful supply of something that a country has"},
    ],
    "phrases": [
        {"phrase": "be used to do sth.", "meaning_zh": "被用来做某事",
         "usage": "被动结构，to后接动词原形",
         "example": "Machines are used to do the work."},
        {"phrase": "be buried deep", "meaning_zh": "被深埋",
         "usage": "常用于科普文描述地下矿藏",
         "example": "Many resources are buried deep inside the Earth."},
        {"phrase": "in search of", "meaning_zh": "寻找",
         "usage": "介词短语，后接名词或动名词",
         "example": "Very large excavators dig up the earth in search of resources."},
        {"phrase": "carry away", "meaning_zh": "运走",
         "usage": "动词短语，强调运送离开",
         "example": "Huge dump trucks carry the resources to where they can be used."},
        {"phrase": "push and pull", "meaning_zh": "推与拉",
         "usage": "成对动词短语，描述力的作用",
         "example": "Tugboats pull barges. They push and pull large ships."},
        {"phrase": "take big bites out of", "meaning_zh": "大口咬下",
         "usage": "形象表达，常用于科普文",
         "example": "Clamlike buckets take big bites out of the earth."},
    ],
    "grammar": [
        {"point": "一般现在时被动语态（Simple Present Passive）",
         "explanation": "结构：主语+am/is/are+过去分词(+by sb.)。当强调动作承受者或不知道执行者时使用，科技说明文高频出现。",
         "examples": [
            "Machines are used to move heavy things.",
            "Loaders are used to dig up dirt and rocks.",
            "Helicopters are used to lift heavy objects.",
         ]},
        {"point": "倍数与数量表达（twice/three times as ... as）",
         "explanation": "倍数+as+adj./adv.+as 表示倍数关系；也可用twice as + adj. + as 表示两倍。",
         "examples": [
            "Their tires are twice as tall as a person.",
            "The Bagger 288 is almost as long as two football fields.",
         ]},
        {"point": "It takes ... to do sth. 结构",
         "explanation": "It takes+时间/金钱+to do sth. 表示做某事需要……，强调付出的代价。",
         "examples": [
            "It takes many big machines to build a tall building.",
            "It took thirty years and a lot of money to build the new palace.",
         ]},
    ],
})

# ===== 2. BIGGER THAN A MONSTER TRUCK =====
LESSONS.append({
    "title_en": "Bigger Than a Monster Truck",
    "word_count": 272,
    "topic": "巨型工程与运输车辆",
    "objectives": {
        "knowledge": [
            "掌握vehicle, bucket, platform, mines等运输/工程类生词",
            "理解倍数表达twice as tall as, as long as 的用法",
            "学习形容词最高级在比较中的运用",
        ],
        "process": [
            "通过对比怪兽卡车与文中更大车辆，激发探究兴趣",
            "运用信息匹配任务训练scanning能力",
            "小组合作完成'交通工具名片'任务，训练归纳能力",
        ],
        "emotions": [
            "感受人类制造巨型机械的创造力",
            "培养对工程科技与未知领域的好奇心",
        ],
    },
    "key_points": [
        "巨型交通工具词汇 (vehicle bridge, dump truck, shovel, tunnel digger)",
        "形容词最高级与倍数表达",
        "一般现在时描述事物特征",
    ],
    "difficult_points": [
        "倍数表达 twice as ... as ... 的使用",
        "历史背景知识（Helepolis古希腊战车）",
    ],
    "methods": ["图片预测法", "比较阅读", "任务驱动教学"],
    "preparation": ["PPT（含车辆图片）", "生词卡", "作业单"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "4分钟",
         "teacher": "播放怪兽卡车视频片段，提问What's even bigger than a monster truck?",
         "students": "观看视频，自由联想并回答。",
         "purpose": "激发兴趣，引入主题。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "出示各车辆图片（鸭式两栖车、车辆桥、起重机、自卸车、陆地列车、太空车），带读生词。",
         "students": "看图认物，跟读生词卡。",
         "purpose": "扫除生词障碍，建立图像与词汇的联结。"},
        {"name": "While-reading（读中）", "duration": "15分钟",
         "teacher": "1. Skim找出文中介绍的几种'比怪兽卡车更大'的车辆；2. Scan完成匹配表；3. 重点讲解twice as tall as a person等比较句型。",
         "students": "速读抓主旨；细读做匹配；小组讨论比较句型。",
         "purpose": "训练阅读策略，落实语言点。"},
        {"name": "Post-reading（读后）", "duration": "8分钟",
         "teacher": "1. 复述：If you were an engineer, which vehicle would you build? 2. 拓展：介绍Bagger 288。",
         "students": "小组讨论并汇报。",
         "purpose": "内化语言，培养表达和思辨能力。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "3分钟",
         "teacher": "总结重点词汇和比较句型，布置分层作业。",
         "students": "记录作业。",
         "purpose": "巩固提升，分层练习。"},
    ],
    "blackboard": (
        "Bigger Than a Monster Truck\n"
        "Duck / Vehicle Bridge / Crane / Dump Truck\n"
        "Overland Train / Power Shovel / Tunnel Digger / Bagger 288\n"
        "★ as ... as ...   ★ twice as tall as a person\n"
        "★ the largest / the biggest"
    ),
    "homework": [
        "必做：抄写本课生词并选其中5个造句（用twice as ... as 或最高级）。",
        "选做：制作一张你最喜欢的巨型车辆名片。",
        "拓展：观看纪录片《MegaStructures》片段，记录3个关于巨型机械的英文词汇。",
    ],
    "vocabulary": [
        {"word": "vehicle", "ipa": "/ˈviːəkl/", "pos": "n.", "meaning_zh": "车辆，运载工具",
         "meaning_en": "a thing used for transporting people or goods on land"},
        {"word": "crush", "ipa": "/krʌʃ/", "pos": "v.", "meaning_zh": "压碎，碾过",
         "meaning_en": "to press something so hard that it breaks or is damaged"},
        {"word": "duck", "ipa": "/dʌk/", "pos": "n.", "meaning_zh": "两栖登陆车；鸭子",
         "meaning_en": "a vehicle that can travel on both land and water"},
        {"word": "bridge", "ipa": "/brɪdʒ/", "pos": "n.", "meaning_zh": "桥梁",
         "meaning_en": "a structure built so people or vehicles can cross over something"},
        {"word": "mine", "ipa": "/maɪn/", "pos": "n.", "meaning_zh": "矿井，矿区",
         "meaning_en": "a place where minerals are dug from the ground"},
        {"word": "tire", "ipa": "/ˈtaɪər/", "pos": "n.", "meaning_zh": "轮胎",
         "meaning_en": "a thick rubber ring that fits around the wheel of a vehicle"},
        {"word": "platform", "ipa": "/ˈplætfɔːrm/", "pos": "n.", "meaning_zh": "平台",
         "meaning_en": "a flat raised surface higher than the area around it"},
        {"word": "shovel", "ipa": "/ˈʃʌvəl/", "pos": "n.", "meaning_zh": "铁铲",
         "meaning_en": "a tool or machine part used for digging and moving earth"},
        {"word": "bucket", "ipa": "/ˈbʌkɪt/", "pos": "n.", "meaning_zh": "铲斗；桶",
         "meaning_en": "a large container attached to a machine for moving earth"},
        {"word": "scoop", "ipa": "/skuːp/", "pos": "v.", "meaning_zh": "舀，铲起",
         "meaning_en": "to pick up something by using a scoop or your hand"},
        {"word": "tunnel", "ipa": "/ˈtʌnəl/", "pos": "n.", "meaning_zh": "隧道，地道",
         "meaning_en": "a long passage under the ground or through a mountain"},
        {"word": "gigantic", "ipa": "/dʒaɪˈɡæntɪk/", "pos": "adj.", "meaning_zh": "巨大的",
         "meaning_en": "extremely large in size or amount"},
        {"word": "ancient", "ipa": "/ˈeɪnʃənt/", "pos": "adj.", "meaning_zh": "古代的",
         "meaning_en": "belonging to a time very long ago in history"},
        {"word": "load", "ipa": "/loʊd/", "pos": "n.", "meaning_zh": "负载；货物",
         "meaning_en": "something that is being carried by a vehicle"},
    ],
    "phrases": [
        {"phrase": "travel on", "meaning_zh": "在…上行驶",
         "usage": "后接交通工具或地点",
         "example": "On land, the Duck moves around on six wheels."},
        {"phrase": "fold up", "meaning_zh": "折叠收起",
         "usage": "动词短语，强调可折叠",
         "example": "When the bridge is no longer needed, it folds up onto the vehicle."},
        {"phrase": "twice as tall as", "meaning_zh": "两倍高",
         "usage": "倍数表达，as ... as 中间放原级",
         "example": "Their tires are twice as tall as a person."},
        {"phrase": "as long as", "meaning_zh": "长达",
         "usage": "表长度，后接具体长度",
         "example": "The Bagger 288 is almost as long as two football fields."},
        {"phrase": "in search of", "meaning_zh": "寻找",
         "usage": "介词短语，书面语常用",
         "example": "Miners use these trucks to carry rocks and dirt."},
        {"phrase": "hard to reach", "meaning_zh": "难以到达的",
         "usage": "复合形容词作后置定语",
         "example": "It is used to carry things into hard-to-reach places."},
    ],
    "grammar": [
        {"point": "形容词最高级（Superlative）",
         "explanation": "结构：the+最高级(+of/in+比较范围)。短形容词加-est；长形容词前加most。",
         "examples": [
            "The world's biggest dump trucks are used at mines.",
            "The Bagger 288 is the largest vehicle in the world.",
         ]},
        {"point": "倍数表达 twice / three times as ... as ...",
         "explanation": "倍数+as+adj./adv.+as 表示倍数关系，是常见比较结构。",
         "examples": [
            "Their tires are twice as tall as a person.",
            "Each wheel is taller than a person.",
         ]},
        {"point": "复合形容词 hard-to-reach / easy-to-use",
         "explanation": "副词+to+动词原形构成复合形容词，中间用连字符，常作定语。",
         "examples": [
            "It is used to carry things into hard-to-reach places.",
         ]},
    ],
})
