"""RAZ Level L Lesson Plans Part 2: Lessons 3-4."""

LESSONS = []

# ===== 3. BLIZZARDS! =====
LESSONS.append({
    "title_en": "Blizzards!",
    "word_count": 491,
    "topic": "暴风雪——成因、危害与防范",
    "objectives": {
        "knowledge": [
            "掌握blizzard, hurricane, whiteout, wind chill等气象类生词",
            "理解blow at speeds of, turn into, make sure 等短语用法",
            "学习一般过去时描述历史事件（1888年大暴风雪）",
        ],
        "process": [
            "通过图片预测激活背景知识",
            "借助流程图梳理暴风雪形成过程",
            "小组讨论如何在大雪天气保护自己，培养批判性思维",
        ],
        "emotions": [
            "感受自然力量的强大，建立敬畏之心",
            "学习防灾意识，关注天气变化",
        ],
    },
    "key_points": [
        "气象类生词 (blizzard, whiteout, wind chill, hurricane, nor'easter)",
        "一般过去时叙述历史事件",
        "形容词的-ing/-ed形式（biting cold vs. interested）",
    ],
    "difficult_points": [
        "blizzard whiteout wind chill 三个相似概念的区分",
        "nor'easter / Alberta Clipper 两类风暴名词",
    ],
    "methods": ["图片环游", "任务型阅读", "小组讨论"],
    "preparation": ["暴风雪相关图片", "生词卡", "维恩图模板"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "播放暴风雪短视频，提问What do you see? How do people feel?",
         "students": "观看视频并讨论。",
         "purpose": "激活背景知识，引入主题。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "出示1888年大暴风雪的老照片，介绍背景；带读生词卡。",
         "students": "看图讨论，跟读生词。",
         "purpose": "建立背景知识，扫除生词。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. Fast reading圈出生词；2. 分段细读；3. 重点讲解turn into, wind chill等词义与用法。",
         "students": "速读抓主旨；细读完成任务单；小组讨论防灾措施。",
         "purpose": "落实词汇与句型，培养阅读策略。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. 维恩图对比blizzard和hurricane；2. 角色扮演：在暴风雪中如何生存？",
         "students": "完成维恩图；小组角色扮演汇报。",
         "purpose": "内化语言，培养防灾意识。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与时态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Blizzards!\n"
        "Three keys: strong winds + blinding snow + freezing cold\n"
        "Wind ≥ 35 mph (≥ 3 hours) = blizzard\n"
        "★ turn ... into ... = 把…变成…\n"
        "★ make sure + 从句 = 确保…"
    ),
    "homework": [
        "必做：抄写本课12个重点词汇并造句。",
        "选做：写一段小短文，描述一次你见过的极端天气。",
        "拓展：查阅中国北方常见的寒潮/暴雪天气，对比blizzard与寒潮。",
    ],
    "vocabulary": [
        {"word": "blizzard", "ipa": "/ˈblɪzərd/", "pos": "n.", "meaning_zh": "暴风雪",
         "meaning_en": "a severe snowstorm with cold temperatures, heavy snow and strong steady winds"},
        {"word": "hurricane", "ipa": "/ˈhɜːrɪkeɪn/", "pos": "n.", "meaning_zh": "飓风",
         "meaning_en": "a strong spinning storm with heavy rain and high winds that starts over an ocean"},
        {"word": "whiteout", "ipa": "/ˈwaɪtaʊt/", "pos": "n.", "meaning_zh": "雪盲；乳白天空",
         "meaning_en": "a situation where blowing snow fills the air and makes it impossible to see"},
        {"word": "wind chill", "ipa": "/wɪnd tʃɪl/", "pos": "n.", "meaning_zh": "风寒（指数）",
         "meaning_en": "the effect of blowing wind that makes the air feel colder than it really is"},
        {"word": "biting", "ipa": "/ˈbaɪtɪŋ/", "pos": "adj.", "meaning_zh": "刺骨的，凛冽的",
         "meaning_en": "painfully cold"},
        {"word": "dangerous", "ipa": "/ˈdeɪndʒərəs/", "pos": "adj.", "meaning_zh": "危险的",
         "meaning_en": "able or likely to cause harm or injury"},
        {"word": "snowstorm", "ipa": "/ˈsnoʊstɔːrm/", "pos": "n.", "meaning_zh": "雪暴，暴风雪",
         "meaning_en": "a storm with heavy snowfall and strong winds"},
        {"word": "gust", "ipa": "/ɡʌst/", "pos": "n.", "meaning_zh": "一阵狂风",
         "meaning_en": "a sudden strong burst of wind"},
        {"word": "freeze", "ipa": "/friːz/", "pos": "v.", "meaning_zh": "结冰；冻结",
         "meaning_en": "to become hard or solid because of extreme cold"},
        {"word": "flashlight", "ipa": "/ˈflæʃlaɪt/", "pos": "n.", "meaning_zh": "手电筒",
         "meaning_en": "a small electric light that you can hold in your hand"},
        {"word": "battery", "ipa": "/ˈbætəri/", "pos": "n.", "meaning_zh": "电池",
         "meaning_en": "a device that produces electricity to power things"},
        {"word": "prepare", "ipa": "/prɪˈper/", "pos": "v.", "meaning_zh": "准备",
         "meaning_en": "to make ready for something that will happen"},
        {"word": "survive", "ipa": "/sərˈvaɪv/", "pos": "v.", "meaning_zh": "幸存；生存",
         "meaning_en": "to stay alive after a dangerous event"},
    ],
    "phrases": [
        {"phrase": "turn ... into ...", "meaning_zh": "把…变成…",
         "usage": "动词短语，强调变化结果",
         "example": "Three things turn a snowstorm into a blizzard."},
        {"phrase": "blow at speeds of", "meaning_zh": "以…速度吹",
         "usage": "描述风速的常用结构",
         "example": "Winds blow at speeds of 35 miles per hour."},
        {"phrase": "last for + 时间", "meaning_zh": "持续…",
         "usage": "表示持续时间",
         "example": "The Great White Hurricane lasted three long days."},
        {"phrase": "make sure", "meaning_zh": "确保",
         "usage": "后接that从句或不接宾语",
         "example": "They can make sure they have batteries and flashlights."},
        {"phrase": "in case of", "meaning_zh": "万一；一旦发生",
         "usage": "介词短语，后接名词",
         "example": "Make sure they have batteries in case of a power loss."},
        {"phrase": "wait out", "meaning_zh": "等到…结束",
         "usage": "动词短语，stay inside until the storm ends",
         "example": "Once prepared, people should settle in and wait out the storm."},
    ],
    "grammar": [
        {"point": "一般过去时叙述历史事件",
         "explanation": "描述过去发生的具体事件，使用动词过去式；常搭配时间状语（in 1888, on Monday）。",
         "examples": [
            "On a March Sunday in 1888, it began to rain in New York.",
            "More than four hundred people had died.",
            "It would be summer before the last of the snow melted.",
         ]},
        {"point": "形容词的-ing/-ed形式（现在分词/过去分词）",
         "explanation": "-ing形式修饰事物或引起感受的事物；-ed形式修饰人。biting cold属于固定搭配。",
         "examples": [
            "Blizzards are known for fierce winds and blowing snow.",
            "The storm caused millions of dollars in damage.",
         ]},
        {"point": "因果连词 because / so",
         "explanation": "because引导原因从句；so引导结果。阅读中常用来梳理事件关系。",
         "examples": [
            "Wind chill causes the body to lose heat faster, so skin feels like it is in much colder air.",
         ]},
    ],
})

# ===== 4. CHICHEN ITZA =====
LESSONS.append({
    "title_en": "Chichen Itza",
    "word_count": 506,
    "topic": "世界遗产——墨西哥玛雅古城奇琴伊察",
    "objectives": {
        "knowledge": [
            "掌握ruins, columns, Maya, cenote, temple 等历史/文化类词汇",
            "理解be made of, be covered with, put in place 等短语",
            "学习一般过去时被动语态（was built, was made）描述历史事件",
        ],
        "process": [
            "通过地图定位Chichen Itza，建立地理概念",
            "借助时间轴梳理玛雅文明历史",
            "小组合作完成'玛雅建筑'主题汇报，培养信息整合能力",
        ],
        "emotions": [
            "感受世界文化遗产的魅力",
            "尊重不同文化，培养国际视野",
        ],
    },
    "key_points": [
        "历史与文化词汇 (ruins, columns, cenote, temple, Maya)",
        "一般过去时被动语态",
        "数字与时间表达（hundreds of years ago）",
    ],
    "difficult_points": [
        "玛雅文化背景知识（cenote, Chac雨神等）",
        "hundreds/thousands/millions of 等数量级的区分",
    ],
    "methods": ["图片环游", "文化渗透", "比较阅读"],
    "preparation": ["奇琴伊察图片/视频", "世界地图", "生词卡"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "展示El Castillo金字塔图片，提问Have you ever seen a pyramid? Where?",
         "students": "看图讨论。",
         "purpose": "激活背景知识，引入玛雅文化。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "在世界地图上定位墨西哥和奇琴伊察，介绍背景；带读生词卡。",
         "students": "看地图，跟读生词。",
         "purpose": "建立地理与文化背景。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 分段细读，按章节完成思维导图（地点/历史/建筑/水源）；2. 重点讲解cenote, ruins等词义及被动语态。",
         "students": "分段阅读并填写思维导图；小组讨论被动句。",
         "purpose": "落实词汇与语法。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. 文化拓展：世界新七大奇迹；2. 小组汇报：你最想去哪个？为什么？",
         "students": "完成拓展任务，小组汇报。",
         "purpose": "内化语言，拓展文化视野。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与被动语态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Chichen Itza\n"
        "Maya people + Yucatan Peninsula + cenote (water)\n"
        "El Castillo / Great Ball Court / Temple of Warriors\n"
        "★ be made of + 材料 = 由…制成\n"
        "★ be covered with = 被…覆盖"
    ),
    "homework": [
        "必做：抄写本课12个重点词汇并造句。",
        "选做：制作一张奇琴伊察的明信片（用英文介绍3-5个景点）。",
        "拓展：选择一项中国世界文化遗产，用英文写一段介绍。",
    ],
    "vocabulary": [
        {"word": "ruins", "ipa": "/ˈruːɪnz/", "pos": "n.", "meaning_zh": "遗迹；废墟",
         "meaning_en": "the remains of an old or destroyed building"},
        {"word": "column", "ipa": "/ˈkɑːləm/", "pos": "n.", "meaning_zh": "柱子",
         "meaning_en": "a tall solid post used as support in a building"},
        {"word": "Maya", "ipa": "/ˈmaɪə/", "pos": "n.", "meaning_zh": "玛雅人",
         "meaning_en": "an ancient people of Central America and southern Mexico"},
        {"word": "temple", "ipa": "/ˈtempəl/", "pos": "n.", "meaning_zh": "寺庙，神殿",
         "meaning_en": "a building used for the worship of a god or gods"},
        {"word": "carve", "ipa": "/kɑːrv/", "pos": "v.", "meaning_zh": "雕刻",
         "meaning_en": "to cut a shape or pattern into a hard material"},
        {"word": "well", "ipa": "/wel/", "pos": "n.", "meaning_zh": "井",
         "meaning_en": "a deep hole dug in the ground to get water, oil or gas"},
        {"word": "jungle", "ipa": "/ˈdʒʌŋɡəl/", "pos": "n.", "meaning_zh": "丛林",
         "meaning_en": "a thick tropical forest"},
        {"word": "peninsula", "ipa": "/pəˈnɪnsələ/", "pos": "n.", "meaning_zh": "半岛",
         "meaning_en": "a piece of land almost surrounded by water"},
        {"word": "pyramid", "ipa": "/ˈpɪrəmɪd/", "pos": "n.", "meaning_zh": "金字塔",
         "meaning_en": "a large stone structure with a square base and four triangular sides"},
        {"word": "ancient", "ipa": "/ˈeɪnʃənt/", "pos": "adj.", "meaning_zh": "古代的",
         "meaning_en": "belonging to a time very long ago in history"},
        {"word": "rainfall", "ipa": "/ˈreɪnfɔːl/", "pos": "n.", "meaning_zh": "降雨；雨水",
         "meaning_en": "the amount of rain that falls"},
        {"word": "worship", "ipa": "/ˈwɜːrʃɪp/", "pos": "v.", "meaning_zh": "崇拜；敬奉",
         "meaning_en": "to show great respect for a god"},
        {"word": "stairs", "ipa": "/sterz/", "pos": "n.", "meaning_zh": "楼梯",
         "meaning_en": "a set of steps built for going from one level to another"},
        {"word": "explore", "ipa": "/ɪkˈsplɔːr/", "pos": "v.", "meaning_zh": "探索",
         "meaning_en": "to travel through a place to learn about it"},
    ],
    "phrases": [
        {"phrase": "be made of", "meaning_zh": "由…制成",
         "usage": "强调材料构成，能看出原材料",
         "example": "They made stone buildings that still stand today."},
        {"phrase": "be covered with", "meaning_zh": "被…覆盖",
         "usage": "被动结构，强调覆盖状态",
         "example": "Suddenly, the men spotted a tall building covered with plants."},
        {"phrase": "in search of", "meaning_zh": "寻找",
         "usage": "介词短语，书面语常用",
         "example": "It took the Maya hundreds of years to build the city."},
        {"phrase": "put ... in place", "meaning_zh": "把…放到合适位置",
         "usage": "强调摆放到位",
         "example": "Every stone had to be carried to the city and put in place by Maya workers."},
        {"phrase": "for hundreds of years", "meaning_zh": "长达数百年",
         "usage": "表时间跨度，复数形式",
         "example": "Most of the land on the peninsula has stayed the same for hundreds of years."},
        {"phrase": "have no ...", "meaning_zh": "没有…",
         "usage": "强调缺乏某物",
         "example": "This part of Mexico has no rivers or lakes."},
    ],
    "grammar": [
        {"point": "一般过去时被动语态（Past Simple Passive）",
         "explanation": "结构：主语+was/were+过去分词(+by sb.)。描述过去的动作承受者或历史事实。",
         "examples": [
            "Chichen Itza was built many hundreds of years ago by the Maya people.",
            "The buildings that the two men saw are called El Castillo.",
            "Today, visitors are not allowed to climb the steps.",
         ]},
        {"point": "数量表达 (hundreds/thousands/millions of + 名词)",
         "explanation": "表示概数，of 后接可数名词复数；hundreds of = 数百。",
         "examples": [
            "There were about three hundred buildings at Chichen Itza.",
            "About fifty thousand people lived in the area.",
            "More than one million people visit Chichen Itza each year!",
         ]},
        {"point": "动词不定式作目的状语 (in order to / to do)",
         "explanation": "动词不定式(to+动词原形)可表目的，相当于in order to。",
         "examples": [
            "Long ago, two men were exploring a jungle in Mexico.",
            "To wear them, I had to practice how to walk in a new way.",
         ]},
    ],
})
