"""RAZ Level L Lesson Plans Part 6: Lessons 11-12."""

LESSONS = []

# ===== 11. MARIA'S FAMILY CHRISTMAS =====
LESSONS.append({
    "title_en": "Maria's Family Christmas",
    "word_count": 353,
    "topic": "玛丽亚一家的圣诞节——多元文化家庭聚会",
    "objectives": {
        "knowledge": [
            "掌握relative, decorate, drape, dessert, tamale 等节日类词汇",
            "理解hang ... from, place ... on, attend church 等短语",
            "学习一般过去时叙事以及be going to / will 表达将来",
        ],
        "process": [
            "通过图片激活节日背景",
            "借助时间轴梳理Christmas Eve到Christmas Day的活动",
            "小组讨论不同文化的节日习俗，培养文化意识",
        ],
        "emotions": [
            "感受家庭温情与分享精神",
            "尊重不同文化背景的节日",
        ],
    },
    "key_points": [
        "节日与家庭词汇 (relatives, decorate, drape, dessert, tamales)",
        "一般过去时 + will / be going to 表达将来",
        "圣诞与新年文化背景",
    ],
    "difficult_points": [
        "西班牙语词汇(abuela, tamale, Navidad)的文化背景",
        "英美与拉美节日文化差异",
    ],
    "methods": ["图片环游", "文化渗透", "情感体验"],
    "preparation": ["圣诞节图片", "生词卡", "拉美节日文化介绍"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "展示各国圣诞节庆祝图片，提问How do you celebrate Christmas in your family?",
         "students": "看图讨论。",
         "purpose": "激活节日背景。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "介绍故事背景（拉美裔家庭在美国过圣诞），带读生词卡。",
         "students": "听介绍，跟读生词。",
         "purpose": "建立背景。"},
        {"name": "While-reading（读中）", "duration": "15分钟",
         "teacher": "1. 分段阅读；2. 完成时间轴（Christmas Eve -> Church -> Christmas morning -> Dinner）；3. 重点讲解decorate, attend等词。",
         "students": "分段阅读并完成时间轴；小组讨论。",
         "purpose": "训练阅读，落实词汇。"},
        {"name": "Post-reading（读后）", "duration": "12分钟",
         "teacher": "1. Discussion：Why did Maria invite Mr. Lewis? 2. Role-play：邀请独居老人一起过节。",
         "students": "讨论；角色扮演。",
         "purpose": "内化语言，培养关爱他人的情感。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "3分钟",
         "teacher": "总结生词与时态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Maria's Family Christmas\n"
        "Christmas Eve -> decorate tree\n"
        "Church -> candles, songs (Spanish & English)\n"
        "Christmas Day -> gifts, dinner with Mr. Lewis\n"
        "★ attend church = 参加教堂活动\n"
        "★ hang ... from ... = 把…挂在…"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：用英文写一段你最喜欢的家庭节日场景。",
        "拓展：学一首简单的英文圣诞歌，记录生词。",
    ],
    "vocabulary": [
        {"word": "relative", "ipa": "/ˈrelətɪv/", "pos": "n.", "meaning_zh": "亲戚",
         "meaning_en": "a member of your family, such as an aunt or cousin"},
        {"word": "decorate", "ipa": "/ˈdekəreɪt/", "pos": "v.", "meaning_zh": "装饰",
         "meaning_en": "to make something look more attractive by adding things to it"},
        {"word": "drape", "ipa": "/dreɪp/", "pos": "v.", "meaning_zh": "披挂；垂放",
         "meaning_en": "to put cloth or a piece of clothing loosely over something"},
        {"word": "glitter", "ipa": "/ˈɡlɪtər/", "pos": "v.", "meaning_zh": "闪闪发光",
         "meaning_en": "to shine with small bright flashes of light"},
        {"word": "dessert", "ipa": "/dɪˈzɜːrt/", "pos": "n.", "meaning_zh": "甜点",
         "meaning_en": "sweet food eaten at the end of a meal"},
        {"word": "tamale", "ipa": "/təˈmɑːli/", "pos": "n.", "meaning_zh": "玉米粽（拉美食物）",
         "meaning_en": "a Mexican food made of corn dough filled with meat and wrapped in corn husks"},
        {"word": "apartment", "ipa": "/əˈpɑːrtmənt/", "pos": "n.", "meaning_zh": "公寓",
         "meaning_en": "a set of rooms for living in, usually on one floor of a building"},
        {"word": "abuela", "ipa": "/əˈbweɪlə/", "pos": "n.", "meaning_zh": "外婆（西班牙语）",
         "meaning_en": "grandmother (Spanish)"},
        {"word": "candle", "ipa": "/ˈkændəl/", "pos": "n.", "meaning_zh": "蜡烛",
         "meaning_en": "a stick of wax with a string inside that is lit to give light"},
        {"word": "roast", "ipa": "/roʊst/", "pos": "v.", "meaning_zh": "烤；烘烤",
         "meaning_en": "to cook food in an oven or over a fire"},
        {"word": "peppermint", "ipa": "/ˈpepərmɪnt/", "pos": "n.", "meaning_zh": "薄荷",
         "meaning_en": "a type of mint used to flavour food and sweets"},
        {"word": "celebrate", "ipa": "/ˈselɪbreɪt/", "pos": "v.", "meaning_zh": "庆祝",
         "meaning_en": "to do something special to show that an event is important or happy"},
    ],
    "phrases": [
        {"phrase": "hang ... from ...", "meaning_zh": "把…挂在…",
         "usage": "动词短语，强调悬挂",
         "example": "Maria hung a tin angel from Mexico on the tree."},
        {"phrase": "place ... on top", "meaning_zh": "把…放在…顶上",
         "usage": "强调顶部位置",
         "example": "Her sister placed a glittering star she had made at school on top."},
        {"phrase": "attend church", "meaning_zh": "去教堂",
         "usage": "动词短语",
         "example": "Maria and her family attended church."},
        {"phrase": "agree with", "meaning_zh": "同意",
         "usage": "动词短语",
         "example": "Her father agreed."},
        {"phrase": "wake early", "meaning_zh": "早早醒来",
         "usage": "动词短语",
         "example": "The next morning, Maria and her cousins woke early."},
        {"phrase": "look up", "meaning_zh": "抬头看",
         "usage": "动词短语",
         "example": "She looked up when Mr. Lewis said, \"I've really enjoyed being here today.\""},
    ],
    "grammar": [
        {"point": "一般过去时 + will / be going to 表将来",
         "explanation": "故事中过去事件用过去式；后续计划用will或be going to。",
         "examples": [
            "It was Christmas Eve. Maria waited for her relatives.",
            "Then he and his family will fly back here.",
        ]},
        {"point": "直接引语与转述动词",
         "explanation": "转述动词(say, ask, answer, exclaim)用过去式，引号内为原话。",
         "examples": [
            "Maria said, \"His smile is like yours.\"",
            "\"Would you like to hold him?\" her aunt asked.",
        ]},
        {"point": "名词所有格 ('s)",
         "explanation": "'s 用于表示有生命的名词的所有关系；Maria's family = 玛丽亚的家庭。",
         "examples": [
            "Maria's Family Christmas",
            "Maria's mother said, \"Let's finish decorating the tree.\"",
        ]},
    ],
})

# ===== 12. NOISE IN THE NIGHT =====
LESSONS.append({
    "title_en": "Noise in the Night",
    "word_count": 537,
    "topic": "露营时夜晚的怪声——幽默故事",
    "objectives": {
        "knowledge": [
            "掌握tent, woods, oak, flashlight, snore 等露营与声音类词汇",
            "理解be fast asleep, wake up, fall asleep 等短语",
            "学习一般过去时连续叙述与时间顺序",
        ],
        "process": [
            "通过声音猜测激活好奇心",
            "梳理故事中的时间顺序（入睡—惊醒—寻声—揭晓）",
            "小组讨论幽默结局，培养推测能力",
        ],
        "emotions": [
            "体会友情的温暖与幽默感",
            "激发对露营等户外活动的好奇",
        ],
    },
    "key_points": [
        "露营与声音词汇 (tent, woods, flashlight, snore, bat)",
        "一般过去时连续叙事",
        "fall asleep / wake up / be fast asleep 等表状态的短语",
    ],
    "difficult_points": [
        "故事中多次声音出现的时序梳理",
        "snore 和 snooze 等近义词辨析",
    ],
    "methods": ["故事教学", "声音猜测", "预测阅读"],
    "preparation": ["露营图片", "故事插图", "生词卡"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "播放各种夜间声音（猫叫、风声、雷声、打鼾声），让学生猜测What is the noise?",
         "students": "听声音并猜测。",
         "purpose": "激活听觉背景，引入主题。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "出示封面（两个男孩和帐篷），提问What could go wrong in a tent at night?",
         "students": "看封面预测。",
         "purpose": "激活背景，预测故事。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 分段阅读；2. 完成'噪音次数'表（几次？Jason的反应？Manuel的反应？）；3. 重点讲解snore, wake up等词。",
         "students": "分段阅读并填写表格；小组讨论。",
         "purpose": "训练阅读，落实词汇。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. Discussion：What would YOU do if you heard a noise at night? 2. Role-play：表演故事的搞笑结尾。",
         "students": "讨论；角色扮演。",
         "purpose": "内化语言，培养口语表达。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与时态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Noise in the Night\n"
        "Sleep -> Noise 1 (Jason wakes, Manuel sleeps)\n"
        "Sleep -> Noise 2 (Manuel wakes)\n"
        "Sleep -> Noise 3 -> It's Dad snoring!\n"
        "★ fall asleep = 入睡\n"
        "★ wake ... up = 叫醒…"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：写一段你露营或在外过夜的趣事（英文）。",
        "拓展：阅读另一个英语幽默故事片段，记录生词。",
    ],
    "vocabulary": [
        {"word": "tent", "ipa": "/tent/", "pos": "n.", "meaning_zh": "帐篷",
         "meaning_en": "a shelter made of cloth and supported by poles, used for camping"},
        {"word": "wood", "ipa": "/wʊd/", "pos": "n.", "meaning_zh": "树林",
         "meaning_en": "an area of land covered with trees"},
        {"word": "oak", "ipa": "/oʊk/", "pos": "n.", "meaning_zh": "橡树",
         "meaning_en": "a large tree that produces acorns"},
        {"word": "flashlight", "ipa": "/ˈflæʃlaɪt/", "pos": "n.", "meaning_zh": "手电筒",
         "meaning_en": "a small electric light that you can hold in your hand"},
        {"word": "snore", "ipa": "/snɔːr/", "pos": "v.", "meaning_zh": "打鼾",
         "meaning_en": "to breathe noisily through the nose and mouth while sleeping"},
        {"word": "asleep", "ipa": "/əˈsliːp/", "pos": "adj.", "meaning_zh": "睡着的",
         "meaning_en": "sleeping"},
        {"word": "frantically", "ipa": "/ˈfræntɪkli/", "pos": "adv.", "meaning_zh": "慌乱地",
         "meaning_en": "in a wild and anxious way"},
        {"word": "grab", "ipa": "/ɡræb/", "pos": "v.", "meaning_zh": "抓起",
         "meaning_en": "to take something quickly"},
        {"word": "whisper", "ipa": "/ˈwɪspər/", "pos": "v.", "meaning_zh": "低声说",
         "meaning_en": "to speak very quietly so that other people cannot hear"},
        {"word": "bother", "ipa": "/ˈbɑːðər/", "pos": "v.", "meaning_zh": "打扰",
         "meaning_en": "to annoy someone or cause them trouble"},
        {"word": "awfully", "ipa": "/ˈɑːfli/", "pos": "adv.", "meaning_zh": "非常；极其",
         "meaning_en": "very; extremely"},
        {"word": "zip", "ipa": "/zɪp/", "pos": "v.", "meaning_zh": "拉上拉链",
         "meaning_en": "to fasten something with a zipper"},
    ],
    "phrases": [
        {"phrase": "be fast asleep", "meaning_zh": "睡得很熟",
         "usage": "形容词短语，强调深度睡眠",
         "example": "Soon Manuel and Jason fell fast asleep."},
        {"phrase": "wake ... up", "meaning_zh": "叫醒",
         "usage": "动词短语，强调唤醒",
         "example": "There was a loud noise, and it woke Jason up."},
        {"phrase": "fall asleep", "meaning_zh": "入睡",
         "usage": "动词短语",
         "example": "Soon Manuel and Jason fell fast asleep."},
        {"phrase": "go back to sleep", "meaning_zh": "重新入睡",
         "usage": "动词短语",
         "example": "\"Now, go back to sleep and stop bothering me.\""},
        {"phrase": "look around", "meaning_zh": "环顾四周",
         "usage": "动词短语",
         "example": "After looking all around, they saw nothing."},
        {"phrase": "out of the still of the dark night", "meaning_zh": "从寂静的黑夜中",
         "usage": "文学化表达",
         "example": "Out of the still of the dark night, they heard the noise again."},
    ],
    "grammar": [
        {"point": "一般过去时连续叙事",
         "explanation": "用过去式按时间顺序讲述故事；常用时间副词then, soon, later, finally衔接。",
         "examples": [
            "They put up a tent in Manuel's yard.",
            "They took sandwiches to the tent and ate their lunch there.",
            "Later, Jason's dad and the family dog went into a tent next to them.",
         ]},
        {"point": "直接引语与转述动词",
         "explanation": "用引号标示原话，转述动词用过去式。",
         "examples": [
            "\"Did you hear that?\" he whispered loudly.",
            "\"Wake up,\" he said. \"I heard it again.\"",
        ]},
        {"point": "连词 and / but / so 表示并列或转折",
         "explanation": "and表顺承；but表转折；so表结果。",
         "examples": [
            "Soon Manuel and Jason fell fast asleep.",
            "Once again, there was a loud noise. And once again, it woke Jason up.",
        ]},
    ],
})
