"""RAZ Level L Lesson Plans Part 4: Lessons 7-8."""

LESSONS = []

# ===== 7. CY AND MEDUSA =====
LESSONS.append({
    "title_en": "Cy and Medusa",
    "word_count": 532,
    "topic": "神话生物的校园友谊故事",
    "objectives": {
        "knowledge": [
            "掌握minotaur, monocle, visor, miracle 等神话与故事类生词",
            "理解turn to stone, make eye contact 等短语",
            "学习一般过去时叙事以及反身代词用法",
        ],
        "process": [
            "激活希腊神话背景（Medusa, Minotaur）",
            "通过人物分析表理解Cy和Medusa的相同处境",
            "小组讨论'差异与友谊'主题，培养共情能力",
        ],
        "emotions": [
            "理解并尊重他人的差异",
            "体会友谊的相互支持",
        ],
    },
    "key_points": [
        "神话与故事类词汇 (minotaur, monocle, visor, miracle)",
        "一般过去时叙事",
        "反身代词 himself/herself 的强调用法",
    ],
    "difficult_points": [
        "希腊神话背景知识",
        "make eye contact with 等短语搭配",
    ],
    "methods": ["故事教学法", "主题阅读", "小组讨论"],
    "preparation": ["希腊神话图片", "故事插图", "生词卡"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "介绍希腊神话中的Medusa（蛇发女妖）和Minotaur（牛头怪），提问：What if they went to school together?",
         "students": "听介绍，预测故事。",
         "purpose": "激活神话背景，引入主题。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "出示插图与生词卡，介绍人物（Cy, Medusa, Mark）。",
         "students": "看图认人物，跟读生词。",
         "purpose": "扫除生词，建立人物图式。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 分段阅读；2. 完成人物对比表（相似点/差异）；3. 重点讲解turn to stone, miracle等词义。",
         "students": "分段阅读并填写对比表；小组讨论。",
         "purpose": "训练比较阅读，落实词汇。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. Discussion：Have you ever been different from others? How did you feel? 2. 续编：What happens next?",
         "students": "小组讨论；续编故事。",
         "purpose": "内化语言，培养共情能力。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与时态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Cy and Medusa\n"
        "Cy (one eye) + Medusa (snake hair) = Friends\n"
        "Visor + Monocle = Solution\n"
        "★ make eye contact with sb. = 与…眼神接触\n"
        "★ turn to stone = 变成石头"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：写一段话介绍你最好的朋友（包括他/她的一个特别的习惯）。",
        "拓展：选一个希腊神话人物，用英文做一段2分钟介绍。",
    ],
    "vocabulary": [
        {"word": "minotaur", "ipa": "/ˈmaɪnətɔːr/", "pos": "n.", "meaning_zh": "牛头怪（希腊神话）",
         "meaning_en": "an imaginary creature that is half man and half bull"},
        {"word": "monocle", "ipa": "/ˈmɑːnəkəl/", "pos": "n.", "meaning_zh": "单片眼镜",
         "meaning_en": "a single round eyeglass worn over one eye"},
        {"word": "visor", "ipa": "/ˈvaɪzər/", "pos": "n.", "meaning_zh": "面罩；护目镜",
         "meaning_en": "a protective shield for the eyes, often attached to a helmet or hat"},
        {"word": "miracle", "ipa": "/ˈmɪrəkəl/", "pos": "n.", "meaning_zh": "奇迹",
         "meaning_en": "a very unusual event that cannot be explained by nature or science"},
        {"word": "direct", "ipa": "/dəˈrekt/", "pos": "adj.", "meaning_zh": "直接的",
         "meaning_en": "going straight from one place to another without stopping"},
        {"word": "shop class", "ipa": "/ʃɑːp klæs/", "pos": "n.", "meaning_zh": "手工课",
         "meaning_en": "a class where students learn practical skills like carpentry or engineering"},
        {"word": "stare", "ipa": "/ster/", "pos": "v.", "meaning_zh": "盯着看",
         "meaning_en": "to look at someone or something for a long time"},
        {"word": "alarm", "ipa": "/əˈlɑːrm/", "pos": "n.", "meaning_zh": "惊慌；警报",
         "meaning_en": "a feeling of fear or worry caused by something dangerous"},
        {"word": "leather", "ipa": "/ˈleðər/", "pos": "n.", "meaning_zh": "皮革",
         "meaning_en": "material made from the skin of animals, used to make clothes and shoes"},
        {"word": "strap", "ipa": "/stræp/", "pos": "n.", "meaning_zh": "带子",
         "meaning_en": "a narrow piece of material used to fasten or hold something"},
        {"word": "carve", "ipa": "/kɑːrv/", "pos": "v.", "meaning_zh": "雕刻",
         "meaning_en": "to cut a pattern into a hard material"},
        {"word": "statue", "ipa": "/ˈstætʃuː/", "pos": "n.", "meaning_zh": "雕像",
         "meaning_en": "a figure of a person or animal made of stone, metal or wood"},
    ],
    "phrases": [
        {"phrase": "turn to stone", "meaning_zh": "变成石头",
         "usage": "动词短语，描述石化",
         "example": "Mark turned to stone."},
        {"phrase": "make eye contact with", "meaning_zh": "与…目光接触",
         "usage": "动词短语，强调对视",
         "example": "Medusa made eye contact with him."},
        {"phrase": "stare at", "meaning_zh": "盯着看",
         "usage": "强调长时间注视",
         "example": "Everyone stares at my one eye."},
        {"phrase": "be late for", "meaning_zh": "迟到",
         "usage": "形容词短语",
         "example": "We need to get to shop class before we're late."},
        {"phrase": "work on", "meaning_zh": "致力于；制作",
         "usage": "强调持续的努力",
         "example": "Cy worked on building a visor."},
        {"phrase": "be an inspiration to", "meaning_zh": "是…的鼓舞",
         "usage": "名词短语，表积极影响",
         "example": "Helen Keller is an inspiration to many people."},
    ],
    "grammar": [
        {"point": "一般过去时叙事 + 反身代词",
         "explanation": "用一般过去时讲述故事；反身代词(myself, himself, herself)用于强调主语本人。",
         "examples": [
            "Cy bumped into Mark, the largest minotaur in the school.",
            "He turned to look, made eye contact with Medusa.",
            "He didn't want to wear his monocle.",
         ]},
        {"point": "感叹句 (What ...! / How ...!)",
         "explanation": "What修饰名词；How修饰形容词或副词。表达强烈情感。",
         "examples": [
            "What a pitcher!",
            "What a miracle!",
        ]},
        {"point": "直接引语与转述动词",
         "explanation": "转述动词(say, ask, answer, cry, add)后接直接引语时用过去式。",
         "examples": [
            "She answered, \"Because I am your fairy godmother!\"",
            "Primo laughed at him, \"You can't try out.\"",
        ]},
    ],
})

# ===== 8. EGGY'S EASY OUT =====
LESSONS.append({
    "title_en": "Eggy's Easy Out",
    "word_count": 395,
    "topic": "棒球接球员Eggy的成长故事",
    "objectives": {
        "knowledge": [
            "掌握catcher, mitt, mask, inning, fastball, pop fly 等棒球词汇",
            "理解signal for, slam into 等短语",
            "学习一般过去时叙述故事",
        ],
        "process": [
            "通过图片激活棒球相关背景",
            "借助时间轴梳理故事的三场比赛",
            "小组讨论Eggy的成长，培养思辨能力",
        ],
        "emotions": [
            "感受兄弟情谊与运动精神",
            "体会努力与坚持的价值",
        ],
    },
    "key_points": [
        "棒球运动词汇 (mitt, mask, fastball, inning, pop fly)",
        "一般过去时叙事",
        "动词过去式的不规则变化",
    ],
    "difficult_points": [
        "棒球术语的理解与运用",
        "动词不规则过去式的准确使用",
    ],
    "methods": ["图片环游", "故事教学", "对比分析"],
    "preparation": ["棒球场地示意图", "生词卡", "故事插图"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "播放棒球精彩瞬间视频，提问What sports do you like? What is your favorite position?",
         "students": "观看视频并讨论。",
         "purpose": "激活运动背景。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "介绍棒球基本位置（pitcher, catcher, batter），带读生词卡。",
         "students": "听介绍，跟读生词。",
         "purpose": "扫除运动术语障碍。"},
        {"name": "While-reading（读中）", "duration": "15分钟",
         "teacher": "1. 分段阅读，梳理三场比赛的进展；2. 重点讲解inning, pop fly等词义。",
         "students": "分段阅读并完成表格（场次/对手/结果）；小组讨论。",
         "purpose": "训练阅读，落实词汇。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. Discussion：What did Eggy learn from his brother? 2. Role-play：采访Eggy。",
         "students": "讨论；角色扮演采访。",
         "purpose": "内化语言，培养思辨能力。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "5分钟",
         "teacher": "总结生词与时态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Eggy's Easy Out\n"
        "Pop-up = 1st game win\n"
        "Tag out = 2nd game lost\n"
        "Catching in the dark = 3rd game\n"
        "★ signal for + 名词 = 发…的信号\n"
        "★ slam into + 名词 = 撞上…"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：写一段话描述你最喜欢的运动及原因。",
        "拓展：学唱英文歌 'Take Me Out to the Ball Game'，记录生词。",
    ],
    "vocabulary": [
        {"word": "catcher", "ipa": "/ˈkætʃər/", "pos": "n.", "meaning_zh": "接球手",
         "meaning_en": "the baseball player who catches pitches that the batter does not hit"},
        {"word": "mitt", "ipa": "/mɪt/", "pos": "n.", "meaning_zh": "棒球手套",
         "meaning_en": "a thick glove used to catch a baseball"},
        {"word": "mask", "ipa": "/mæsk/", "pos": "n.", "meaning_zh": "护面罩",
         "meaning_en": "a covering for the face to protect it"},
        {"word": "inning", "ipa": "/ˈɪnɪŋ/", "pos": "n.", "meaning_zh": "局（棒球）",
         "meaning_en": "one of the nine periods of play in a baseball game"},
        {"word": "fastball", "ipa": "/ˈfæstbɔːl/", "pos": "n.", "meaning_zh": "快速球",
         "meaning_en": "a baseball pitch thrown very fast"},
        {"word": "pop fly", "ipa": "/pɑːp flaɪ/", "pos": "n.", "meaning_zh": "高飞球",
         "meaning_en": "a baseball that is hit high into the air"},
        {"word": "nickname", "ipa": "/ˈnɪkneɪm/", "pos": "n.", "meaning_zh": "昵称",
         "meaning_en": "an informal name given to someone"},
        {"word": "sneeze", "ipa": "/sniːz/", "pos": "v.", "meaning_zh": "打喷嚏",
         "meaning_en": "to suddenly let out air through the nose and mouth"},
        {"word": "batter", "ipa": "/ˈbætər/", "pos": "n.", "meaning_zh": "击球手",
         "meaning_en": "the baseball player who tries to hit the ball"},
        {"word": "awesome", "ipa": "/ˈɑːsəm/", "pos": "adj.", "meaning_zh": "了不起的",
         "meaning_en": "extremely good or impressive"},
        {"word": "toss", "ipa": "/tɔːs/", "pos": "v.", "meaning_zh": "扔；抛",
         "meaning_en": "to throw something lightly"},
        {"word": "lump", "ipa": "/lʌmp/", "pos": "n.", "meaning_zh": "肿块",
         "meaning_en": "a hard swelling on the body"},
    ],
    "phrases": [
        {"phrase": "signal for + 名词", "meaning_zh": "发…信号",
         "usage": "动词短语，发信号要求某种球",
         "example": "I signaled for a fastball."},
        {"phrase": "slam into + 名词", "meaning_zh": "撞上…",
         "usage": "动词短语，强调猛烈撞击",
         "example": "Fastballs zoom past the batter and slam hard into my mitt."},
        {"phrase": "tag out", "meaning_zh": "触杀",
         "usage": "棒球术语，触杀出局",
         "example": "I tagged a player out as she slid home."},
        {"phrase": "throw off", "meaning_zh": "甩掉；脱下",
         "usage": "动词短语，强调脱掉",
         "example": "I flung off my mask."},
        {"phrase": "black out", "meaning_zh": "昏过去",
         "usage": "动词短语，短暂失去意识",
         "example": "Before I blacked out, my mitt reached for the ball."},
        {"phrase": "be known as", "meaning_zh": "被称为",
         "usage": "被动语态，强调名称",
         "example": "Jordan has always liked to throw things, especially at me."},
    ],
    "grammar": [
        {"point": "一般过去时叙事",
         "explanation": "用动词过去式讲述过去发生的事；规则动词加-ed，不规则动词特殊变化。",
         "examples": [
            "During the last inning of our first game, I signaled for a fastball.",
            "The batter hit a pop fly.",
            "That's when the ball hit my head.",
         ]},
        {"point": "动词不规则过去式 (fling-flung, throw-threw, hit-hit)",
         "explanation": "常用不规则变化：fling-flung, throw-threw/thrown, hit-hit, lose-lost, win-won, catch-caught, slide-slid。",
         "examples": [
            "I flung off my mask.",
            "The batter knocked it straight over my head.",
        ]},
        {"point": "When / Before / That's when 引导时间状语从句",
         "explanation": "表时间的连词可连接两个动作发生的先后顺序。",
         "examples": [
            "That's when I really tried to forget that Jordan was there.",
            "Before I blacked out, my mitt reached for the ball.",
        ]},
    ],
})
