"""RAZ Level L Lesson Plans Part 3: Lessons 5-6."""

LESSONS = []

# ===== 5. CINDERELLO =====
LESSONS.append({
    "title_en": "Cinderello",
    "word_count": 447,
    "topic": "棒球版改编灰姑娘故事",
    "objectives": {
        "knowledge": [
            "掌握chore, guffaw, pitcher, spatula, transform, tryout 等故事类词汇",
            "理解dream of, try on, slip on 等短语用法",
            "学习一般过去时叙述故事（died, married, forbade, transformed）",
        ],
        "process": [
            "激活已知灰姑娘故事，进行版本对比",
            "通过时间轴梳理故事情节",
            "小组角色扮演复述故事，培养口语表达能力",
        ],
        "emotions": [
            "感受改编故事的幽默与创意",
            "体会善良与努力终有回报",
        ],
    },
    "key_points": [
        "故事类生词 (chores, guffawed, spatula, transformed, tryouts)",
        "一般过去时叙事",
        "dream of / try on / slip on 短语",
    ],
    "difficult_points": [
        "与原版灰姑娘的对比理解",
        "guffawed, spatula 等较生僻词",
    ],
    "methods": ["故事教学法", "角色扮演", "比较阅读"],
    "preparation": ["故事插图", "灰姑娘原版对比卡", "角色扮演头饰"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "讲原版灰姑娘故事片段，提问What if Cinderella was a boy? What if he liked baseball?",
         "students": "听故事，预测改编版。",
         "purpose": "激活背景，引入主题。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "出示封面（棒球男孩），带读生词卡；介绍人物关系（Mateo, Primo, Guapo）。",
         "students": "看封面，跟读生词，讨论人物。",
         "purpose": "扫除生词，建立人物图式。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 分段阅读，每段讨论how is it like/different from Cinderella；2. 重点讲解过去时与短语。",
         "students": "分段阅读，做对比表格；小组讨论。",
         "purpose": "训练比较阅读，落实语言点。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. 角色扮演：分组扮演Mateo, Primo, Guapo, fairy godmother；2. 续编故事：What happens next?",
         "students": "角色扮演展示；续编故事。",
         "purpose": "内化语言，培养创造力。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与过去时，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Cinderello (棒球版灰姑娘)\n"
        "Mateo + stepbrothers + fairy godmother\n"
        "Chores -> Tryouts -> Magic -> Win -> Slipper\n"
        "★ dream of + doing = 梦想做…\n"
        "★ try on = 试穿"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：续写Cinderello的故事（5-8句英文）。",
        "拓展：把故事讲给家人听，并用英文介绍3个主角的性格。",
    ],
    "vocabulary": [
        {"word": "chore", "ipa": "/tʃɔːr/", "pos": "n.", "meaning_zh": "家务杂事",
         "meaning_en": "a small job or task that must be done regularly"},
        {"word": "guffaw", "ipa": "/ɡəˈfɔː/", "pos": "v.", "meaning_zh": "哄笑；大笑",
         "meaning_en": "to laugh suddenly and loudly"},
        {"word": "pitcher", "ipa": "/ˈpɪtʃər/", "pos": "n.", "meaning_zh": "投手",
         "meaning_en": "the baseball player who throws the ball to the batter"},
        {"word": "spatula", "ipa": "/ˈspætʃələ/", "pos": "n.", "meaning_zh": "锅铲",
         "meaning_en": "a long-handled kitchen tool with a flat surface used to lift or mix food"},
        {"word": "transform", "ipa": "/trænsˈfɔːrm/", "pos": "v.", "meaning_zh": "使改观；改变",
         "meaning_en": "to change completely in form or appearance"},
        {"word": "tryout", "ipa": "/ˈtraɪaʊt/", "pos": "n.", "meaning_zh": "选拔赛",
         "meaning_en": "an event to test how good someone is at a sport or activity"},
        {"word": "runt", "ipa": "/rʌnt/", "pos": "n.", "meaning_zh": "小个子",
         "meaning_en": "the smallest and weakest animal in a group, or a small weak person"},
        {"word": "spoiled", "ipa": "/spɔɪld/", "pos": "adj.", "meaning_zh": "被宠坏的",
         "meaning_en": "treated too well, so that you behave badly"},
        {"word": "greedy", "ipa": "/ˈɡriːdi/", "pos": "adj.", "meaning_zh": "贪婪的",
         "meaning_en": "wanting more food, money, etc. than you need"},
        {"word": "bully", "ipa": "/ˈbʊli/", "pos": "v.", "meaning_zh": "欺凌",
         "meaning_en": "to repeatedly hurt or frighten someone who is weaker"},
        {"word": "uniform", "ipa": "/ˈjuːnɪfɔːrm/", "pos": "n.", "meaning_zh": "制服",
         "meaning_en": "a special set of clothes worn by members of the same group"},
        {"word": "forbid", "ipa": "/fərˈbɪd/", "pos": "v.", "meaning_zh": "禁止",
         "meaning_en": "to order someone not to do something"},
        {"word": "tease", "ipa": "/tiːz/", "pos": "v.", "meaning_zh": "取笑",
         "meaning_en": "to laugh at someone or say unkind things about them"},
    ],
    "phrases": [
        {"phrase": "dream of + doing", "meaning_zh": "梦想做…",
         "usage": "后接名词或动名词",
         "example": "There was once a young boy named Mateo who dreamed of becoming a great baseball player."},
        {"phrase": "be overjoyed", "meaning_zh": "欣喜若狂",
         "usage": "形容词短语，表极度高兴",
         "example": "They were overjoyed."},
        {"phrase": "try on", "meaning_zh": "试穿",
         "usage": "动词短语，强调穿戴尝试",
         "example": "He had every boy try on the shoe."},
        {"phrase": "slip on", "meaning_zh": "穿上",
         "usage": "动词短语，强调快速穿上",
         "example": "When the shoe slipped on perfectly, they both gasped."},
        {"phrase": "lead ... to ...", "meaning_zh": "带领…通往…",
         "usage": "动词短语，表引向结果",
         "example": "Mateo will be our captain, and he will lead us to victory!"},
        {"phrase": "be thrilled", "meaning_zh": "非常兴奋",
         "usage": "形容词短语，表强烈喜悦",
         "example": "Mateo was thrilled."},
    ],
    "grammar": [
        {"point": "一般过去时叙事",
         "explanation": "用动词过去式（规则加-ed，不规则特殊变化）讲述过去发生的事。常与时间状语连用。",
         "examples": [
            "Mateo's father died. His death left Mateo and his mother very sad.",
            "Mateo's mother married a rich man.",
            "His father agreed, and he forbade Mateo from trying out.",
         ]},
        {"point": "反身代词 (himself/herself)",
         "explanation": "用于强调主语本人；也用在某些动词后（enjoy himself, hurt himself）。",
         "examples": [
            "The twins teased and bullied Mateo.",
            "He had been at school long enough to know about her powers.",
         ]},
        {"point": "动词过去式的不规则变化",
         "explanation": "常见不规则：come-came, run-ran, see-saw, give-gave, take-took, win-won, lose-lost, find-found, think-thought, lead-led, slip-slipped。",
         "examples": [
            "Mateo lost one shoe, but he got free and ran home.",
            "The coach spotted Mateo.",
         ]},
    ],
})

# ===== 6. CROCS AND GATORS =====
LESSONS.append({
    "title_en": "Crocs and Gators",
    "word_count": 600,
    "topic": "鳄鱼家族——分类、特征与生活习性",
    "objectives": {
        "knowledge": [
            "掌握crocodilian, snout, predator, prey, jaw 等爬行动物词汇",
            "理解spend time on, tear apart 等短语",
            "学习一般现在时描述动物特征与分类",
        ],
        "process": [
            "通过图片分类（alligator/crocodile/caiman/gharial）建立分类图式",
            "借助表格比较四种鳄鱼的异同",
            "讨论人类与动物的关系（保护/捕猎）",
        ],
        "emotions": [
            "培养对爬行动物的科学认识",
            "建立保护濒危动物的意识",
        ],
    },
    "key_points": [
        "动物分类与特征词汇 (crocodilian, snout, predator, prey)",
        "一般现在时描述动物习性",
        "nowhere to/from 等不定代词短语",
    ],
    "difficult_points": [
        "alligator/crocodile/caiman/gharial 区分",
        "生存保护话题的延伸讨论",
    ],
    "methods": ["图片环游", "比较阅读", "科学阅读"],
    "preparation": ["四种鳄鱼对比图", "维恩图模板", "生词卡"],
    "process": [
        {"name": "Lead-in（导入）", "duration": "5分钟",
         "teacher": "展示鳄鱼图片，提问Do you know the difference between a crocodile and an alligator?",
         "students": "观察图片，尝试回答。",
         "purpose": "激活背景，引入主题。"},
        {"name": "Pre-reading（读前）", "duration": "5分钟",
         "teacher": "介绍爬行动物(reptile)的特征；带读生词卡。",
         "students": "听介绍，跟读生词。",
         "purpose": "建立背景知识。"},
        {"name": "While-reading（读中）", "duration": "18分钟",
         "teacher": "1. 分段阅读；2. 完成四种鳄鱼对比表；3. 重点讲解snout, predator等词。",
         "students": "细读课文并填写对比表；小组讨论。",
         "purpose": "训练信息整合，落实词汇。"},
        {"name": "Post-reading（读后）", "duration": "10分钟",
         "teacher": "1. Discussion：Why are crocodilians endangered? What should we do? 2. 角色扮演：你是一只鳄鱼宝宝，向同学介绍自己。",
         "students": "讨论；角色扮演。",
         "purpose": "内化语言，培养保护意识。"},
        {"name": "Summary & Homework（小结与作业）", "duration": "2分钟",
         "teacher": "总结生词与时态，布置作业。",
         "students": "记录作业。",
         "purpose": "巩固。"},
    ],
    "blackboard": (
        "Crocs and Gators\n"
        "Alligator - short broad snout (USA/China)\n"
        "Crocodile - narrow snout, teeth stick out (global)\n"
        "Caiman - Central/South America\n"
        "Gharial - long narrow snout, fish-eater (India)\n"
        "★ spend time on + V-ing = 花时间做…"
    ),
    "homework": [
        "必做：抄写12个重点词汇并造句。",
        "选做：制作一张你最喜爱的爬行动物海报（英文介绍）。",
        "拓展：阅读关于扬子鳄(yangtze alligator)的英文资料，记录5个生词。",
    ],
    "vocabulary": [
        {"word": "crocodilian", "ipa": "/ˌkrɑːkəˈdɪliən/", "pos": "n.", "meaning_zh": "鳄鱼（含鳄、鼉、凯门鳄等）",
         "meaning_en": "any member of the group of reptiles that includes crocodiles, alligators, caimans and gharials"},
        {"word": "reptile", "ipa": "/ˈreptaɪl/", "pos": "n.", "meaning_zh": "爬行动物",
         "meaning_en": "an animal whose body temperature changes with the air temperature and that lays eggs"},
        {"word": "snout", "ipa": "/snaʊt/", "pos": "n.", "meaning_zh": "口鼻部",
         "meaning_en": "the long nose and mouth of an animal such as a crocodile"},
        {"word": "predator", "ipa": "/ˈpredətər/", "pos": "n.", "meaning_zh": "捕食者",
         "meaning_en": "an animal that hunts and eats other animals"},
        {"word": "prey", "ipa": "/preɪ/", "pos": "n.", "meaning_zh": "猎物",
         "meaning_en": "an animal that is hunted and eaten by another animal"},
        {"word": "jaw", "ipa": "/dʒɔː/", "pos": "n.", "meaning_zh": "颌，下巴",
         "meaning_en": "the lower part of the face, including the mouth and teeth"},
        {"word": "swamp", "ipa": "/swɑːmp/", "pos": "n.", "meaning_zh": "沼泽",
         "meaning_en": "an area of land that is covered with shallow water"},
        {"word": "nostril", "ipa": "/ˈnɑːstrəl/", "pos": "n.", "meaning_zh": "鼻孔",
         "meaning_en": "one of the two openings at the end of the nose"},
        {"word": "scale", "ipa": "/skeɪl/", "pos": "n.", "meaning_zh": "鳞片",
         "meaning_en": "one of the small flat pieces of hard material that cover fish and reptiles"},
        {"word": "endangered", "ipa": "/ɪnˈdeɪndʒərd/", "pos": "adj.", "meaning_zh": "濒危的",
         "meaning_en": "an animal or plant that may soon disappear forever"},
        {"word": "incubator", "ipa": "/ˈɪŋkjubeɪtər/", "pos": "n.", "meaning_zh": "孵化器",
         "meaning_en": "a machine for keeping eggs warm so that baby animals can hatch"},
        {"word": "survive", "ipa": "/sərˈvaɪv/", "pos": "v.", "meaning_zh": "生存；幸存",
         "meaning_en": "to stay alive"},
    ],
    "phrases": [
        {"phrase": "spend time on + V-ing", "meaning_zh": "花时间做…",
         "usage": "强调花费时间做某事",
         "example": "Crocodilians spend time on land and in water."},
        {"phrase": "be similar to", "meaning_zh": "与…相似",
         "usage": "形容词短语，比较相似性",
         "example": "The shape of their head is similar to that of a crocodile."},
        {"phrase": "tear ... apart", "meaning_zh": "撕碎",
         "usage": "动词短语，描述捕食动作",
         "example": "They either swallow it whole or tear it apart."},
        {"phrase": "swallow ... whole", "meaning_zh": "整吞",
         "usage": "强调未经咀嚼",
         "example": "They cannot chew their food. They either swallow it whole or tear it apart."},
        {"phrase": "keep ... in balance", "meaning_zh": "保持…平衡",
         "usage": "强调生态平衡",
         "example": "Protecting them helps to keep nature in balance."},
        {"phrase": "in many parts of", "meaning_zh": "在…许多地区",
         "usage": "介词短语，表范围广",
         "example": "In many parts of the world, people kill crocodilians for food."},
    ],
    "grammar": [
        {"point": "一般现在时描述动物特征",
         "explanation": "用一般现在时陈述动物的客观特征与习性，第三人称单数动词加-s/-es。",
         "examples": [
            "Alligators have short, broad snouts.",
            "Crocodilians use lungs to breathe.",
            "They can also shut off their windpipe.",
         ]},
        {"point": "由that引导的定语从句",
         "explanation": "that作关系代词，指代前面的名词，引导定语从句修饰名词。",
         "examples": [
            "They even look a little like some of the dinosaurs from long ago.",
            "Most live in fresh water.",
            "Crocodilians are hard to see in water.",
         ]},
        {"point": "并列复合句 (and / but / or)",
         "explanation": "用and, but, or连接并列分句，表达并列、转折或选择关系。",
         "examples": [
            "They eat animals as big as deer and cattle, and as small as fish and birds.",
            "They cannot chew their food, but they can swallow it whole or tear it apart.",
         ]},
    ],
})
